services:
  backend:
    build: backend
    depends_on:
      database:
        condition: service_healthy
    environment:
      - PGURI=${PGURI}
    ports:
      - '3000:3000'

  database:
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    healthcheck:
      interval: 1s
      test: 'pg_isready --username=postgres'
    image: postgres
    ports:
      - '5433:5432'
    volumes:
      - ./data:/var/lib/postgresql/data

  frontend:
    build:
      context: frontend
    depends_on:
      - backend
    ports:
      - '80:80'
