services:
  backend:
    build:
      context: ./backend
    # networks:
    #   - slm-network
    # networks:
    #   - slm-network
    depends_on:
      database:
        condition: service_healthy
    environment:
      - PGURI=${PGURI}
      # - JWT_SECRET=${JWT_SECRET}
    ports:
      - '3000:3000'
    # volumes:
    #   - ./backend:/app
    #   - /app/node_modules

  database:
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    # networks:
    #   - slm-network
    # networks:
    #   - slm-network
    healthcheck:
      interval: 1s
      test: 'pg_isready --username=postgres'
    image: postgres
    ports:
      - '5433:5432'
    volumes:
      - ./data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
    # networks:
    #   - slm-network
    # networks:
    #   - slm-network
    depends_on:
      - backend
    ports:
      - '80:80'
# networks:
#   slm-network:
#     driver: bridge

# networks:
#   slm-network:
#     driver: bridge
